### ISSUE TITLE
JavaFX post Java 11

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-demos#52]
Java 11 will remove JavaFX from the JDK. Try to use OpenFX instead.

**Comment by Daniel-Dos** [comment]
Hi, 

do you think it would be better to create a new module pointing to Java 11 or upgrade the existing one?

here a few links to use javafx-11:

https://openjfx.io/openjfx-docs/#maven

https://mvnrepository.com/artifact/org.openjfx

**Comment by keilw** [comment]
Do as you like, we could also follow the pattern of other demos e.g. `uom-console-demos-java10` or uom-`console-demos-unicode-java10` and create `uom-fxlib-java11` (this would follow the pattern of other modules) The existing `uom-fxlib` is still based on `uom-se`, so it does not have to be changed. We may in the 2.0 codebase actually think of migrating it to `indriya`, but that doesn't mean it must run under Java 11. The only other alternative would be a `multi-release-jar`, but I cannot say, if and how it could deal with multiple dependencies for a particular JVM version?

**Comment by keilw** [comment]
Thanks it all builds against Java 11 here now. Actually since the old JFX demos won't build between Java 9 and 10 for some reason I think it's best to replace the `uom-fxlib` with what's now `uom-fxlib-java11`. There is a 1.0 branch of the entire demos which builds against Java SE 8. With Java 8 and 11 being the two current LTS versions that looks like a good foundation.

**Comment by keilw** [comment]
Update to 17.0.5
