### ISSUE TITLE
Spring Boot Demo

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-demos#64]
A Spring Boot application that does Unit conversion either via Web interface or REST endpoints

**Comment by koaben** [comment]
Hi Keil, thanks for your good advices. Lars and I have created an example with SpringBoot here https://github.com/NLxAROSA/uom-sb-demo

**Comment by thodorisbais** [comment]
Done! [This](https://github.com/Adopt-a-JSR/jsr385-demos) repo now contains all our work, thanks a lot!

**Comment by thodorisbais** [comment]
Would be nice to include the fore-mentioned demo in this repo as well.

**Comment by thodorisbais** [comment]
Closed with 27dc9b0f954845fe026253de1ad4585f8a6ad44c
