### ISSUE TITLE
Why are we using uom-se for our demos?

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/uom-demos#68]
Is there a specific reason we are (still) using `uom-se` along with `indriya` dependency for our demos?
If not, I'd like to update it to have a look at it to remove `uom-se`.

![Screenshot 2019-06-11 at 20 38 27](https://user-images.githubusercontent.com/5684688/59297654-02fc2d00-8c89-11e9-97c8-e6e47f06f524.png)

**Comment by keilw** [comment]
If you look at the timestamps, these started in 2014 when Indriya did not exist. They are there for compatibility reasons, we might want an `1.x` branch similar to Indriya itself, then the master branch could subsequently reduce the old implementations, but e.g. Java ME 8 would either die or still use `unit-ri`.

**Comment by thodorisbais** [comment]
Cool, not urgent for now then. Closing, thanks, Werner.
