### ISSUE TITLE
Create video demos and upload them on YouTube

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/uom-demos#69]

**Comment by thodorisbais** [comment]
Uploaded video for spring boot demo.

**Comment by thodorisbais** [comment]
Uploaded video for Vaadin demo

**Comment by keilw** [comment]
Where is the link? We could add a "blog" / news page for either the PR, Adopt-day or a combination of both with links to selected YouTube videos.

**Comment by thodorisbais** [comment]
- Link for Spring Boot demo: https://www.youtube.com/watch?v=VlQ2gM9iSlQ
- Link for Vaadin demo: https://www.youtube.com/watch?v=ggO5Du3DQYE

**Comment by keilw** [comment]
Is this done?

**Comment by thodorisbais** [comment]
I was planning to record one more video for Kotlin repl, but I'm having some trouble there.
All in all, that can be done later as well, so, closing for now.
