### ISSUE TITLE
Experiment with Valhalla

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-demos#71]
This is a very early exploration, but whenever Project [Valhalla](https://jdk.java.net/valhalla/) makes it into the JDK it could be very useful to this JSR at least on an implementation level.

**Comment by keilw** [comment]
See http://hg.openjdk.java.net/valhalla/valhalla/file/45f2f8d86692/test/jdk/valhalla/valuetypes for examples

**Comment by thodorisbais** [comment]
Is this still valid after [your first investigation](https://github.com/unitsofmeasurement/uom-demos/tree/master/console/valhalla)?

**Comment by keilw** [comment]
Let's keep that one open, but there is not much to do till it evolves.

**Comment by thodorisbais** [comment]
I would say the goal of this issue is met and it could be closed (so that it also doesn't create any confusion to other visitors of our issues page), but I'm fine with keeping it open for a while as well.

**Comment by keilw** [comment]
Keep it open at least till OC1, there could be some people interested in this or even something new to hear (although I am not sure, if it's a priority for the JDK team)
