### ISSUE TITLE
temperature-converter demo on WildFly 17

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/uom-demos#72]
Tried to run the temperature-converter demo on WildFly v17.0.1.Final

That was only possible by adjusting a bit the instructions on README:

- `version.org.jboss.as.plugins.maven.plugin` value set to `17.0.1.Final` and
- running `mvn clean package jboss:deploy` instead of `mvn clean package jboss-as:deploy`

Shall we also add the following note?

```java 
...
    mvn clean package jboss-as:deploy // older JBoss installations


    mvn clean package jboss:deploy // WilfFly 17 and newer
...
```

**Comment by keilw** [comment]
I used 17 as well but I did the deployment via WTP on Eclipse.

If the plugin changed that way and it isn't backward compatible (did you try using the new plugin with Wildfly 15 or 14?) then we could update the README.

Of course it should be possible to also use other Jakarta EE (Java EE) runtimes ;-)

**Comment by thodorisbais** [comment]
I am using IntelliJ and that was the only way to make it work.
There is always a chance I'm missing something, but of course, I think it's important to also run it without any plugins, so I'm gonna add that small reference and in case we find a better solution in the future, we can always adjust it, but for now, it would be good to also serve IntelliJ users.

**Comment by thodorisbais** [comment]
@keilw shall we maybe completely update the demo to be WildFly-compatible? I don't really think there's anyone using JBoss on development nowadays

**Comment by keilw** [comment]
I just deployed it on Thorntail, creates a 130 MB FAT JAR but does not require an IDE ;-)

**Comment by thodorisbais** [comment]
Bad phrasing from my side. I only refer to this command:

`mvn clean package jboss-as:deploy`

which should be like below when it is about a WildFly server:

`mvn clean package jboss:deploy`

**Comment by keilw** [comment]
It still won't work:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.332 s
[INFO] Finished at: 2019-09-02T23:49:03+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:jboss-maven-plugin:1.3.1:deploy (default-cli) on project temperature-converter: Mojo error occurred: Connection refused: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by thodorisbais** [comment]
Maybe because you also need to set your `version.org.jboss.as.plugins.maven.plugin` accordingly (`17.0.1.Final` for my example) ?

**Comment by keilw** [comment]
This is bad, my entire Thorntail readme got lost due to a merge conflict 👎

**Comment by keilw** [comment]
Luckily the local history prevented the worst;-) 
The profiles are inspired by https://github.com/javaee-samples/javaee8-samples, if we can it would be nice to add further containers like Payara or Glassfish.
