### ISSUE TITLE
Use ResourceBundles to handle internationalization for the HeatRequirementDemo

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/uom-demos#76]
The [`HeatRequirementDemo`](https://github.com/unitsofmeasurement/uom-demos/blob/master/domain/energy/src/main/java/tech/uom/demo/energy/HeatRequirementDemo.java) printout is currently hardcoded in German.

Using `ResourceBundle` to provide internationalization would be nice.

**Comment by sukanth** [comment]
@keilw  @thodorisbais  Added Internationalization using ResourceBundle in PR# https://github.com/unitsofmeasurement/uom-demos/pull/90

**Comment by keilw** [comment]
@sukanth Unfortunately the properties are not working, will fix them, if possible in future please use Unicode characters for umlauts etc. that usually works.

**Comment by sukanth** [comment]
Hey, @keilw it works on my machine.. not sure why it's not working for you. 
![image](https://user-images.githubusercontent.com/8810504/87258679-10c34980-c46b-11ea-9ebd-607a906d9c15.png)

**Comment by keilw** [comment]
@sukanth Your console shows the problem already, it should say:
````
Welche Arbeit ist nötig um 1000 l Wasser von 50°C auf 70°C zu erhitzen?
23.33333333333333333333333333333333 kWh
Wenn nur 9.5 kW zur Verfügung stehen dauert es entsprechend länger.
Nämlich: 2.456140350877192982456140350877193 h
````
And not something like "NÃ¤mlich".

**Comment by sukanth** [comment]
> @sukanth Your console shows the problem already, it should say:
> 
> ```
> Welche Arbeit ist nötig um 1000 l Wasser von 50°C auf 70°C zu erhitzen?
> 23.33333333333333333333333333333333 kWh
> Wenn nur 9.5 kW zur Verfügung stehen dauert es entsprechend länger.
> Nämlich: 2.456140350877192982456140350877193 h
> ```
> 
> And not something like "NÃ¤mlich".

Aww !! Got it. Thanks for fixing it.

**Comment by keilw** [comment]
Installing the ResourceBundle Editor from the MarketPlace can help if you use Eclipse. I assume there must be a similar plugin for IntelliJ, but I have not tried that so far.
