### ISSUE TITLE
Health module doesn't build

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/uom-demos#77]
During our preparation for JCON with @keilw, we found out that the [`health`](https://github.com/unitsofmeasurement/uom-demos/tree/master/domain/health) module does not compile; there must be a dependency error.

It seems to be a low hanging fruit, but it needs further investigation.
![Screenshot 2019-09-25 at 13 58 28](https://user-images.githubusercontent.com/5684688/65598936-def4fb00-df9c-11e9-90c3-4f4935e7f705.png)

**Comment by andi-huber** [comment]
Or rather a test the fails!?

**Comment by sukanth** [comment]
fixed this in PR https://github.com/unitsofmeasurement/uom-demos/pull/90
