### ISSUE TITLE
HeatRequirementDemo is broken by Indriya 2.0.3

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-demos#91]
When testing the i18n of the [HeatRequirementDemo](https://github.com/unitsofmeasurement/uom-demos/blob/master/domain/energy/src/main/java/tech/uom/demo/energy/HeatRequirementDemo.java) I stumbled over a problem with that demo because for the  RELATIVE heat and similar calculations everything is turned into system units. After the upgrade to Indriya 2.0.3 the sentence
"Um 1000l von 50°C auf 70°C zu erhöhen ist eine Arbeit von 23,33KWh nötig." 
becomes
"Um 1000l von 50°C auf 70°C zu erhöhen ist eine Arbeit von 0.02333333333333333333333333333333333kWh nötig." 
As it seems `LITRE` gets converted into the SI unit `m³` causing this?
The only way to fix this currently is to tweak it by multiplying the result by 1000 (line 64), so @andi-huber could you please in JavaDoc or a code comment address this problem by explaining why that's necessary?
The original page is German, so it shouldn't be a problem. I know this used at least one or two casts that may seem weird, but similar to e.g. the CO2 demos the results and formulas are mathematically sound and worked up until the changes made to Indriya 2.0.3.

**Comment by andi-huber** [comment]
fixed

**Comment by keilw** [comment]
In Indriya or in the demo?

**Comment by andi-huber** [comment]
demo

**Comment by keilw** [comment]
That looks very consistent, thanks a lot. I am thinking of adding a locale parameter like "en" or so, but the fallback would be German for this one because of the webpage.
